name: Build and Release Docker Image

on:
  workflow_run:
    workflows: ["Check Upstream Version"]  # Name of your first workflow
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - 'new_version.txt'
      - 'Dockerfile'
      - 'entrypoint.sh'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: guniv/coolercontrol-docker
  PROJECT_ID: 30707566

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # ... [previous steps remain the same until release notes generation]

      - name: Generate Release Notes
        id: release-notes
        run: |
          NOTES_FILE="release_notes.md"
          touch $NOTES_FILE
          
          if [[ "${{ steps.version.outputs.IS_NEW_UPSTREAM }}" == "true" ]]; then
            # Get and clean upstream notes
            curl -s --header "PRIVATE-TOKEN: ${{ secrets.GL_PAT }}" \
              "https://gitlab.com/api/v4/projects/$PROJECT_ID/releases/${{ steps.version.outputs.UPSTREAM_VERSION }}" \
              | jq -r '.description' | sed 's/ (![0-9]\+)//g' > upstream_notes.md
            
            # Add CoolerControl changes section with link
            if [[ -s upstream_notes.md ]]; then
              echo "## CoolerControl Changes" >> $NOTES_FILE
              cat upstream_notes.md >> $NOTES_FILE
              echo -e "\n[View full release notes](https://gitlab.com/coolercontrol/coolercontrol/-/releases/${{ steps.version.outputs.UPSTREAM_VERSION}})" >> $NOTES_FILE
            fi
          fi

          # Get Docker changes
          SINCE_DATE=$(git log -1 --format=%cd --date=iso-strict origin/main)
          git log --pretty=format:"- %s" --since="$SINCE_DATE" -- Dockerfile entrypoint.sh > docker_changes.md

          # Add Docker updates section if there are changes
          if [[ -s docker_changes.md ]]; then
            echo -e "\n## Docker-specific Updates" >> $NOTES_FILE
            cat docker_changes.md >> $NOTES_FILE
          fi

          echo "NOTES_FILE=$NOTES_FILE" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.UPSTREAM_VERSION }}-docker${{ steps.version.outputs.DOCKER_BUILD }}
          name: ${{ steps.version.outputs.UPSTREAM_VERSION }}${{ steps.version.outputs.IS_NEW_UPSTREAM != 'true' && format('-docker{0}', steps.version.outputs.DOCKER_BUILD) || '' }}
          body_path: ${{ steps.release-notes.outputs.NOTES_FILE }}
          draft: false
          prerelease: false

      - name: Update Version Tracker
        if: steps.version.outputs.IS_NEW_UPSTREAM == 'true'
        run: |
          echo "${{ steps.version.outputs.UPSTREAM_VERSION }}" > last_release.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add last_release.txt
          git commit -m "Track upstream version ${{ steps.version.outputs.UPSTREAM_VERSION }}"
          git push origin main
