name: Manual Push to GHCR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., "v1.2.3")'
        required: true
      build-number:
        description: 'Build number (e.g., "1")'
        required: true
        default: '1'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: guniv/coolercontrol-docker

jobs:
  push-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.version }}-docker${{ inputs.build-number }}
